use_frameworks!
platform :ios, '8.0'

target 'VerticalSteppedSlider_Example' do
  pod 'VerticalSteppedSlider', :path => '../'

  target 'VerticalSteppedSlider_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
